<a href="https://colab.research.google.com/github/stefanocostantini/pytorch-book/blob/master/ch3_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Packages
import torch

In [ ]:
# Check if runtime has GPU
torch.cuda.is_available()

True

In [ ]:
# tensor data structure --> generalisation of vectors and matrices to an arbitrary
# number of dimentions. 
# number of indices == number of dimensions

In [ ]:
a = torch.ones(3)

In [ ]:
a

tensor([1., 1., 1.])

In [ ]:
a[2]=2.0

In [ ]:
a

tensor([1., 1., 2.])

In [ ]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [ ]:
# Or
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [ ]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [ ]:
# Let's instead use a 2D tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [ ]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points.shape

torch.Size([3, 2])

In [ ]:
# It can also be initialised with zeros or ones, specifying the dimensions
points = torch.zeros(3,2)

In [ ]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# Individual elements can now be accessed using 2 indices
points[0,0]

tensor(4.)

In [ ]:
# or two get all elements for one dimension, just specify the other
points[0]

tensor([4., 1.])

In [ ]:
# Now using range indexing
points[1:] # all rows after the first one

tensor([[5., 3.],
        [2., 1.]])

In [ ]:
points[1:, 0] # all rows after the first one, first column

tensor([5., 2.])

In [ ]:
# Named tensors, to keep track of what each dimension represents
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

/pytorch/c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


In [ ]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
# We can use refine_names for adding/modifying names of an already existing tensor
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]

In [ ]:
img_t_names = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [ ]:
img_t_names.shape

torch.Size([3, 5, 5])

In [ ]:
img_t_names.names

('channels', 'rows', 'columns')

In [ ]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

In [ ]:
weights_named.shape

torch.Size([3])

In [ ]:
# For operations with 2 inputs, in addition to the dimension check, PyTorch also 
# checks the names. We however need to manually align the dimensions
# This results in an error --> weights_named * img_t_names

RuntimeError: ignored

In [ ]:
# but this does not
weights_aligned = weights_named.align_as(img_t_names)

In [ ]:
weights_aligned.shape

torch.Size([3, 1, 1])

In [ ]:
# So we can do
prod = weights_aligned * img_t_names
prod.shape, prod.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [ ]:
# If we try to combine dimentions with different names, we get an error

In [ ]:
# note that if we want to use tensorts outside functions that operate on named 
# tensors, we need to drop the names by renaming them to `None`

In [ ]:
# Objects within a tensor must all be numbers of the same type. Some examples
# Default data type for tensors is 32-bit floating point --> computations happening
# in neural networks are typically executed with 32-bit floating point precision.

torch.float64

In [ ]:
a = points > 1

In [ ]:
a.dtype

torch.bool

In [ ]:
# To allocate a tensor of the right numeric type, we can specify the proper dtype
# as an argument to the constructor
double_points = torch.ones(10, 2, dtype=torch.double)

In [ ]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [ ]:
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [ ]:
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [ ]:
# or
short_points = torch.ones(10,2).short()

In [ ]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [ ]:
# or using the 'to' method
double_points = torch.zeros(10,2).to(torch.double)

In [ ]:
# Tensor API
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
# or
a_t = a.transpose(0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
# a small set of operations exist only as methods of the Tensor object, and 
# they are recognisable from a trailing underscore in their name, e.g.
a_zero = a.zero_()
a_zero

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0],[5.0, 3.0], [2.0, 1.0]], device='cuda:0')

In [ ]:
# or
points_gpu = points.to(device='cuda')

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_cpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
# can also do
points_gpu = points.cuda()

In [ ]:
# Interoperability with NumPy
points = torch.ones(3,4)

In [ ]:
points_np = points.numpy()

In [ ]:
points_np

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [ ]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
points = torch.ones(3,4,2)

In [ ]:
points

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
points = torch.from_numpy(points_np)

In [ ]:
points.shape

torch.Size([3, 4, 2])

In [ ]:
a = list(range(9))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
a_t = torch.tensor(a)

In [ ]:
a_t.shape

torch.Size([9])

In [ ]:
a_t.size()

torch.Size([9])

In [ ]:
a_t.stride()

(1,)

In [ ]:
b_t = a_t.view(3,3)

In [ ]:
b_t

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
b_t.storage(), a_t.storage()

( 0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9])

In [ ]:
c_t=b_t[1:,1:]

In [ ]:
c_t.stride()

(3, 1)

In [ ]:
c_t

tensor([[4, 5],
        [7, 8]])

In [ ]:
a_t = a_t.to(torch.double).sqrt_()

In [ ]:
a_t

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)